export const cardArray = [
  {
    id: 0,
    title: 'Первый товар',
    price: '171 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 1,
    title: 'Второй товар',
    price: '172 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 2,
    title: 'Третий товар',
    price: '173 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 3,
    title: 'Четвёртый товар',
    price: '174 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 4,
    title: 'Пятый товар',
    price: '175 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 5,
    title: 'Шестой товар',
    price: '176 ₽',
    address: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
];

export const sideArray = [
  {
    id: 0,
    title: 'Доставка',
    img: '/image/side-info-1.svg',
    description: 'Проверка при получении и возможность бесплатно вернуть товар',
  },
  {
    id: 1,
    title: 'Автотека',
    img: '/image/side-info-2.svg',
    description: 'Отчёт с историей авто: пробег, владельцы, сведения о залоге, ДТП и ремонтах',
  },
  {
    id: 2,
    title: 'Онлайн-бронирование жилья',
    img: '/image/side-info-3.svg',
    description: 'Посуточная аренда квартир и домов: большой выбор вариантов для поездок по России',
  },
];
